### ISSUE TITLE
Drugs Übersetzung

### ISSUE THREAD

**Issue by AurelioSilver** [AurelioSilver/pillarsofeternity-2-german-patch#33]
Drugs wurde als Drogen übersetzt. Teilweise aber auch mit Arzneien. In Poe1 war es Arzneinen. 

In den Mönchtexten heisst es immer Drogen. 

Worauf einigen wir uns?

**Comment by Xaratas** [comment]
Also son Weißblatt hat außer der berauschenden Wirkung jetzt nicht so viele Einsatzzwecke.
Kann man schon Drogen nennen.

**Comment by AurelioSilver** [comment]
Mir geht's dann um solche Texte.

Cyclopedia:
<DefaultText>Arzneien</DefaultText>
<DefaultText>Arzneien können innerhalb oder außerhalb des Kampfes eingesetzt werden, um langandauernde Boni zu erhalten, aber wenn ihr Effekt abklingt, leidet der Anwender bis zum nächsten Rasten unter einem Abzug.</DefaultText>

Gui
<DefaultText>Kann keine Nahrung, Getränke oder Arzneien verwenden</DefaultText>
<DefaultText>{0} kann keine Nahrung, Getränke oder Arzneien verwenden.</DefaultText>
<DefaultText>{0} Wirkungsdauer von Arzneien</DefaultText>

Beim Mönch heisst es dann Drogen...

Unter den Absturzeffekten eines Drogen-Verbrauchsgegenstandes können Nalpazca-Mönche keinerlei Heilung bekommen.
Alle Drogeneffekte haben eine verlängerte Wirkungsdauer.
Abzüge, die durch den Absturz von Drogen entstehen, machen es dem Mönch unmöglich, geheilt zu werden.
Wunden zersetzen sich, wenn man keine Vorteile von Drogen erhält.

**Comment by AurelioSilver** [comment]
Crash penalties from drugs cause the monk to be unable to receive healing.

Könnte man, denke ich. Das sind die ganzen Texte von den Charakterklassen.

**Comment by AurelioSilver** [comment]
Texte wurden umgeschrieben
