### ISSUE TITLE
Patch 2.0.0 Änderungen

### ISSUE THREAD

**Issue by AurelioSilver** [AurelioSilver/pillarsofeternity-2-german-patch#40]
Es fehlen noch in exported:
- [x] Abilities
- [x] Gui
- [x] Cyclopedia

Beast of Winter Texte:
- [x] Anführungsstriche
- [x] Klammern überprüfen, etc

**Comment by Xaratas** [comment]
Tool kommt wenn das ander durch ist, Abilities mach ich gerade.

**Comment by AurelioSilver** [comment]
Darum hab ich ja gerade die Liste gemacht. :) Ich bin für heute erstmal durch. Rest ist mir aktuell zuviel. Abilities ist allein schon ein ganzer Batzen...

**Comment by Xaratas** [comment]
Da hast du recht. Bei id 1337 und ich bin nicht mehr aufnahmefähig.

**Comment by AurelioSilver** [comment]
Ja, so ging es mir auch immer. Immer die Änderungen der neuen deutschen Version mit der Version davor verglichen, dann mit unsererer und dann noch gegen die englische, um zu sehen, ob die Änderung überhaupt stimmt...
