### ISSUE TITLE
Patch 2.1.0 Änderungen

### ISSUE THREAD

**Issue by AurelioSilver** [AurelioSilver/pillarsofeternity-2-german-patch#42]
Bisher habe ich nur neue Texte und Korrekturen von Patch 2.1.0 übernommen.

Aktueller Git Status https://github.com/AurelioSilver/pillarsofeternity-2-german-patch/commit/26bb79b4148e1cecd1cbb31d017175f73537f626 sollte kompatibel mit Patch 2.0.1 sein. Man könnte dafür eine neue Finale Version bauen.

Ich bin nur 2 Wochen im Urlaub und habe daher keine Zeit mehr. Viele Änderungen habe ich schon eingeplegt, aber es gibt z. B. in den abilities texten noch viel zum koorigieren / überprüfen.

Vielleicht kannst du @Xaratas das übernehmen?

**Comment by Xaratas** [comment]
Ich kann da mal reinschauen. Und gefühlt ist eh eine Version fällig.
